repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.389
    hooks:
      - id: pyright

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.0.2
    hooks:
      - id: stylua

  # luacheck is intentionally NOT using a repo hook
  # because it *required* LuaRocks to be installed
  - repo: local
    hooks:
      - id: luacheck
        name: luacheck
        entry: luacheck
        language: system
        types: [lua]
        pass_filenames: false
        args: [., --exclude-files, src, examples]
