repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.389
    hooks:
      - id: pyright

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.0.2
    hooks:
      - id: stylua
        args: ['--respect-ignores']

  # luacheck is intentionally NOT using a repo hook
  # because it *required* LuaRocks to be installed
  - repo: local
    hooks:
      - id: luacheck
        name: luacheck
        entry: luacheck
        language: system
        types: [lua]
        pass_filenames: false
        args: [., --exclude-files, src, examples, 'benchmarks/**/reference_*.lua']

      - id: forbid-nested-functions
        name: Forbid nested function definitions in Lua files
        language: system
        entry: >
          sh -c '
            if grep -nEr "	(local function|function)" --include="*.lua" .; then
              echo "Error: Nested function definitions found in Lua files."
              exit 1
            fi
          '
        pass_filenames: false
