name: CI Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install LuaJIT and Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit libluajit-5.1-dev cmake build-essential

      - name: Clone and build grug-tests
        run: |
          git clone https://github.com/grug-lang/grug-tests
          cd grug-tests
          cmake -S . -B build
          cmake --build build

      - name: Run tests
        run: luajit tests.lua "" ./grug-tests

lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
