name: CI Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Lua 5.1
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1

      - name: Run script
        run: lua5.1 hello.lua
